first_homepage:
    path:     /
    defaults: { _controller: FirstBundle:Default:index }

second_homepage:
    path:     /hello/{name}.{_format}
    defaults: { _controller: FirstBundle:Default:sayHello , _format: html }

seccion1:
    path:     /seccion1
    defaults: { _controller: FirstBundle:Default:seccion1 }

seccion2:
    path:     /seccion2
    defaults: { _controller: FirstBundle:Default:seccion2 }

seccion3:
    path:     /seccion3
    defaults: { _controller: FirstBundle:Default:seccion3 }
